### ISSUE TITLE
User Story 2 - Add buttons

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/userStories#2]
## Value Proposition

**As a User** 

**I want an App** 
to see my current gym plan. 

**to be able to:**
- adjust the plan, so the user can add the part, which is needed. 

## Description
![UserStory2 (1)](https://user-images.githubusercontent.com/115224131/206910565-0076f70a-8cbd-4b72-a274-e2146ea00e03.png)

## Acceptance Criteria

- [ ] Page which has 4 buttons, which include the parts:  Warm-Up, Squat, Bench, Deadlift & Assistant
- [ ] The corresponding button can be used to add the part. 
- [ ] The added section should be editable for the user. 

## Tasks

(for developers team)
- [ ] Use new branch, to add the buttons. 
- [ ] Create 4 buttons to each exercise part. 
- [ ] Function: handleClick for each section, so only the part which is clicked, will be shown.

**Comment by AntjeWalter** [comment]
Hi Kirsten, ich bin mir gerade unsicher, ob ich es richtig verstanden habe. Wenn ich auf den "Add Exercise" Button drücke, dann wird die jeweilige Exercise direkt darunter dupliziert und die Liste quasi erweitert? Find ich eine gute Lösung, um eine zweite Seite (mit z.B. einem neuen Plan) erstmal zu umgehen :)
