### ISSUE TITLE
User Story 3 - Add Delete Buttons

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/userStories#3]
## Value Proposition

**As a User** 

**I want an App** 
- to see my current gym plan. 

**to be able to:**
- adjust the plan, so the user can **add & delete** the part, which is needed. 

## Description
![UserStory3 (1)](https://user-images.githubusercontent.com/115224131/206912341-e97078d1-4251-4f0b-b034-69d19c1f4bc4.png)

## Acceptance Criteria

- [ ] Page has Buttons to add each Exercise Part as section. 
- [ ] Each Section (Warm-Up, Squat, Bench, Deadlift, Assistant) has a delete Button. 

## Tasks

(for developers team)
- [ ] Use new branch, to add the "delete" buttons for each section. 
- [ ] Add delete Button for each section.
