### ISSUE TITLE
US # 6 - Add delete Button for "set" Part

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/userStories#6]
## Value Proposition

**As a User** 

**I want an App: ** 
- to have an app for my Powerlifting Workout. 

**to be able to:**
- to adjust my plan, to which will be done for the day. 

## Description
![image](https://user-images.githubusercontent.com/115224131/207082118-9e4abd89-b2f1-4431-a307-7ec69568347f.png)

## Acceptance Criteria

- [ ] show delete button, when set will be swiped to the left. 

## Tasks

(for developers team)
- [ ] each set will have a swipe function.
- [ ] set can be swiped to the left & keep in place => sticks to the position. 
- [ ] while in swiped position, the delete button will be shown. 
- [ ] click on delete button = deletes the set.
