### ISSUE TITLE
US #7 - Outsource "Gym Plan Code" to a new page & link it to a button

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/userStories#7]
## Value Proposition

**As a User** 

**I want an App: ** 
- to have an app for my Powerlifting Workout. 

**to be able to:**
- to adjust my plan, to which will be done for the day. 

## Acceptance Criteria

- [ ] If "+" button is clicked, the gym plan will be seen, which is editable. 

## Tasks

(for developers team)
- [ ] add new component "button--addPlan" 
- [ ] Component "button--addPlan" has a Link, which will lead to a new page / component. 
- [ ] outsource the code of "Gym Plan" to the new component.
- [ ] the Gym Plan is now visible, when the component "button--addPlan" is clicked.
